/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jniTravel_JNITravel */

#ifndef _Included_jniTravel_JNITravel
#define _Included_jniTravel_JNITravel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jniTravel_JNITravel
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jniTravel_JNITravel_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
